<?php

namespace App\Http\Requests\Admin\News;

use Illuminate\Foundation\Http\FormRequest;

class NewsCreateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules(): array
    {
        return [
            'category_id' => ['required', 'int'],
            'title' => ['required', 'string', 'min:5'],
            'description' => ['required', 'string', 'min:50'],
            'author' => ['required', 'string', 'min:2']
        ];
    }

    public function messages(): array
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }

    public function attributes(): array
    {
        return [
            'category_id' => 'Название категории',
            'title' => 'Название новости',
            'description' => 'Текст новости',
            'author' => 'Автор'
        ];
    }
}
